// <auto-generated />
using System;
using Kolora.Orcamentos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kolora.Orcamentos.Data.Migrations
{
    [DbContext(typeof(KoloraDbContext))]
    [Migration("20260903033258_AddCamposPagamento")]
    partial class AddCamposPagamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Kolora.Orcamentos.Models.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GraficaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Kolora.Orcamentos.Models.Entities.ConfiguracoesGrafica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GraficaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Iban")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MargemPadraoGlobal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("MensagemRodapePdf")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MulticaixaExpressNumero")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeExibicaoPdf")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ValidadePadraoDias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(3);

                    b.HasKey("Id");

                    b.HasIndex("GraficaId")
                        .IsUnique();

                    b.ToTable("ConfiguracoesGrafica");
                });

            modelBuilder.Entity("Kolora.Orcamentos.Models.Entities.Grafica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Graficas");
                });

            modelBuilder.Entity("Kolora.Orcamentos.Models.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GraficaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockAtual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Materiais");
                });

            modelBuilder.Entity("Kolora.Orcamentos.Models.Entities.Orcamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaminhoPdf")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GraficaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItensJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Validade")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orcamentos");
                });

            modelBuilder.Entity("Kolora.Orcamentos.Models.Entities.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusSync")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TentativasEnvio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoOperacao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimoErro")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("StatusSync");

                    b.ToTable("OutboxEvents");
                });

            modelBuilder.Entity("Kolora.Orcamentos.Models.Entities.PedidoOrcamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteNome")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteTelefone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEmOrigem")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoPedido")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GraficaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrcamentoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProdutoDesejado")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Quantidade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RecebidoLocalEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TextoOriginalCliente")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PedidosOrcamento");
                });

            modelBuilder.Entity("Kolora.Orcamentos.Models.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GraficaId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MargemPadrao")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoCustoBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoCalculo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Kolora.Orcamentos.Models.Entities.ProdutoMaterial", b =>
                {
                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConsumoPorUnidade")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ProdutoId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("ProdutoMateriais");
                });

            modelBuilder.Entity("Kolora.Orcamentos.Models.Entities.SyncState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UltimoPullCatalogo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimoPullPedidos")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersaoSchemaLocal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SyncState");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            VersaoSchemaLocal = 1
                        });
                });

            modelBuilder.Entity("Kolora.Orcamentos.Models.Entities.ProdutoMaterial", b =>
                {
                    b.HasOne("Kolora.Orcamentos.Models.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolora.Orcamentos.Models.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
